### ISSUE TITLE
Bloom struct types limit filter size

### ISSUE THREAD

**Issue by p0pr0ck5** [jvirkki/libbloom#14] opened 2018-03-11 21:39 UTC
When trying to build fairly large, low-error rate filter (10^10 entries, 0.00001 error rate), `bloom_init` fails because `entries`, `bits`, and `bytes` are signed integers. Would you consider a patch that adjusts these type definitions to something like `uint64_t`, or something similar/appropriate, to allow for significantly large filter sizes? I understand that wide platform support is a goal for this project.

For the curious, my use case was building a filter for the HIBP password list (~500 million entries) with varying error levels.

**Comment by jvirkki** [comment] 2018-03-11 21:58
That seems fine.

I don't know if anyone has written code accessing these fields but technically they are documented to be part of the public interface in the bloom struct. That means changing the types will not be binary compatible, so I'd have to delay merging this until a 2.0 release.

**Comment by jvirkki** [comment] 2019-02-19 08:18
I finally had a chance to experiment with changing the sizes to uint64_t. It caused a performance regression of about 20%.
For 2.0, I'll be changing these to unsigned int instead. That is large enough to handle the HIBP password list (and more) and no performance regression.
If larger sets become interesting (let me know), will need to explore other alternatives.

**Comment by jvirkki** [comment] 2019-03-30 08:07
Fixed in 2.0

**Closed as completed by jvirkki** 2019-03-30 08:07 UTC

**Comment by albertobsd** [comment] 2021-01-09 05:35
Hi i have some issues, i think this is a good place to ask,
I want to create a bloom filter with 316227767 elements

The init params was the next
```
bloom_init(&bloom,316227767,0.001);
```
I incremente the error value and works, but with biggers entries the bloom_init fails.

I expected to work with entries  values like 1Billion or 2Billions 


```
int main()  {
  struct bloom bloom;
  uint32_t items = 1016227767;
  if(bloom_init(&bloom,items,0.1) == 1) {
    fprintf(stderr,"[E] error bloom_init for %u elements.\n",items);
    exit(0);
  }
}
```

What is the best workaround to handle this issue?
Wher is hte version 2? I only see the version 1.6

Kind Regards!

**Comment by jvirkki** [comment] 2021-01-09 08:32
Please see branch info here:
https://github.com/jvirkki/libbloom/blob/master/docs/branches

The development branch contains the (unreleased) changes. Since the size type is an incompatible change, it'll need to be a new major release (2.0).
